### ISSUE TITLE
Backend Controller

### ISSUE THREAD

**Issue by Ncp294** [ankitgoyal0106/Swap-Shop#93]
**Feature Name**: Backend Controllers

**Description**:

Implement ProfileController singleton class which does CRUD operations using the ProfileModelFactory to retrieve, edit, create, and delete profiles.
Implement ChatController singleton class which does CRUD operations using the ChattingModelFactory to retrieve, edit, create, and delete profiles.

**Point Value**: [Specify the point value, e.g., 1-2 for small, 3-4 for medium, 5-6 for large]

**Size Category**: [Small, Medium, or Large]

**Owner**: Tyler Tang

**Comments/Feedback**:

- Team members should discuss the feature here, providing feedback, suggesting improvements, or pointing out potential challenges.
- [Name of Team Member] on [Date]: [Comment or feedback text]

**Decision**:

- Final comment indicating whether the feature will be included, who will implement it, and any necessary adjustments.

**Comment by ttang859** [comment]
Resolve with #151
